#!/usr/bin/env php
<?php

use Scraper\Models\Extractor;
use Scraper\Models\SimpleHttpClient;
use Scraper\Models\Scraper;

require "vendor/autoload.php";

$args = (new \samejack\PHP\ArgvParser())->parseConfigs($argv);

$elements = isset($args['elements']) ? explode(',', $args['elements']) : [];
$excludes = isset($args['excludes']) ? explode(',', $args['excludes']) : [];
$insideClass = isset($args['inside-class']) ? $args['inside-class'] : null;
$metaTags = isset($args['meta-tags']) ? explode(',', $args['meta-tags']) : [];

$sitemap = $args['sitemap'];

$extractor = new Extractor();
$httpClient = new SimpleHttpClient();

$extractor->setElements($elements);
$extractor->setMetaTags($metaTags);
$extractor->setInsideClass($insideClass);

$scraper = new Scraper($sitemap, $httpClient, $extractor);
$scraper->exclude($excludes);

$json = json_encode($scraper->fetch(), JSON_UNESCAPED_UNICODE);
if (file_put_contents(dirname(__FILE__) . "/exports/" . date("Y-m-d H-i") . ".json", $json)) {
    print_r("JSON file created successfully.\n");
}
